apiVersion: v1
kind: ConfigMap
metadata:
  name: cart-configmap
  namespace: roboshop
  labels:
    name: cart
    environment: dev
    type: app
data:
  REDIS_HOST: 'redis'
  CATALOGUE_HOST: 'catalogue'
  CATALOGUE_PORT: '8080'

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart
  namespace: roboshop
  labels: #repica set labels
    name: cart
    environment: dev
    type: app
spec:
  replicas: 1
  selector: # These are the labels replica set use to create pod replicas, this should match pod labels
    matchLabels:
      name: cart
      environment: dev
      type: app
  template: # This is pod definition
    metadata:
      name: cart
      labels: 
        name: cart
        environment: dev
        type: app
    spec:
      containers:
      - name: cart
        image: kusumasoumya/cart:v1
        envFrom:
        - configMapRef:
            name: cart-configmap
---
apiVersion: v1
kind: Service
metadata:
  name: cart
  namespace: roboshop
  labels: 
    name: cart
    environment: dev
    type: app
spec:
  selector:
    name: cart
    environment: dev
    type: app
  ports:
    - protocol: TCP
      port: 8080 #service port
      targetPort: 8080 #container port


