apiVersion: v1
kind: Pod
metadata: 
  name: multicontainer Pod
  labels:
    name: multicontaoner Pod
spec:
  containers: 
  - name: nginx
    image: nginx
  - name: almalinux
    image: almalinux
    container: ["sleep", "1000"]

