apiVersion: v1
kind: Pod
metadata: 
  name: multicontainer
  labels:
    name: multicontaoner
spec:
  containers: 
  - name: nginx
    image: nginx
  - name: almalinux
    image: almalinux
    command: ["sleep", "1000"]

