apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: replica-demo
  labels: #repica set labels
    name: roboshop
    environment: dev
spec:
  replicas: 3
  selector:
    matchLables:
      name: roboshop
  template:
    metadata:
      name: roboshop
    spec:
      containers:
      - name: nginx
        image: nginx
