apiVersion: v1
Namespace: roboshop
kind: pod
metadata:
  name: service-demo
  labels: 
    name: roboshop
    environment: dev
spec:
  containers:
    - name: nginx
      image: nginx

---

apiVersion: v1
kind: service
metadata:
  name: service-demo
  labels: service-demo
spec:
  selector:
    name: roboshop
    environment: dev
  ports:
    - protocol: TCP
      port: 80 #service port
      targetPort: 80 #container port
