apiVersion: v1
kind: Service
metadata:
  name: service-np
  labels: 
    name: servicedemo
spec:
  type: NodePort
  selector:
    name: roboshop
    environment: dev
  ports:
    - protocol: TCP
      port: 80 #service port
      targetPort: 80 #container port
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-np
  labels: 
    name: roboshop
    environment: dev
spec:
  containers:
    - name: nginx
      image: nginx



