apiVersion: v1
kind: ConfigMap
metadata:
  name: shipping-configmap
  namespace: roboshop
  labels:
    name: shipping
    environment: dev
    type: app
data:
  CART_ENDPOINT: "cart:8080" 
  DB_HOST: "mysql"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shipping
  namespace: roboshop
  labels: #repica set labels
    name: shipping
    environment: dev
    type: app
spec:
  replicas: 1
  selector: # These are the labels replica set use to create pod replicas, this should match pod labels
    matchLabels:
      name: shipping
      environment: dev
      type: app
  template: # This is pod definition
    metadata:
      name: shipping
      labels: 
        name: shipping
        environment: dev
        type: app
    spec:
      containers:
      - name: shipping
        image: kusumasoumya/shipping:v1
        envFrom:
        - configMapRef:
            name: shipping-configmap
---
apiVersion: v1
kind: Service
metadata:
  name: shipping
  namespace: roboshop
  labels: 
    name: shipping
    environment: dev
    type: app
spec:
  selector:
    name: shipping
    environment: dev
    type: app
  ports:
    - protocol: TCP
      port: 8080 #service port
      targetPort: 8080 #container port


