apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: roboshop
  labels:
    name: mysql
    environment: dev
    type: database
type: Opaque
data:
  MY_SQL_ROOT_PASSWORD: 'RoboShop@1'
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: roboshop
  labels: #repica set labels
    name: mysql
    environment: dev
    type: database
spec:
  replicas: 1
  selector: # These are the labels replica set use to create pod replicas, this should match pod labels
    matchLabels:
      name: mysql
      environment: dev
      type: database
  template: # This is pod definition
    metadata:
      name: mysql
      labels: 
        name: mysql
        environment: dev
        type: database
    spec:
      containers:
      - name: mysql
        image: kusumasoumya/mysql:v1
        envFrom:
        - secretRef:
            name: mysql-secret
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: roboshop
  labels: 
    name: mysql
    environment: dev
    type: database
spec:
  selector:
    name: mysql
    environment: dev
    type: database
  ports:
    - protocol: TCP
      port: 3306 #service port
      targetPort: 3306 #container port


