apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secret
  namespace: roboshop
  labels:
    name: rabbitmq
    environment: dev
    type: database
type: Opaque
data:
  RABBITMQ_DEFAULT_USER: 'cm9ib3Nob3A='
  RABBITMQ_DEFAULT_PASS: 'cm9ib3Nob3AxMjM='
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  namespace: roboshop
  labels: #repica set labels
    name: rabbitmq
    environment: dev
    type: database
spec:
  replicas: 1
  selector: # These are the labels replica set use to create pod replicas, this should match pod labels
    matchLabels:
      name: rabbitmq
      environment: dev
      type: database
  template: # This is pod definition
    metadata:
      name: rabbitmq
      labels: 
        name: rabbitmq
        environment: dev
        type: database
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:3
        envFrom:
        - secretRef:
            name: rabbitmq-secret
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: roboshop
  labels: 
    name: rabbitmq
    environment: dev
    type: database
spec:
  selector:
    name: rabbitmq
    environment: dev
    type: database
  ports:
    - protocol: TCP
      port: 5672 #service port
      targetPort: 5672 #container port


