apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-configmap
  namespace: roboshop
  labels:
    name: catalogue
    environment: dev
    type: app
data:
  MONGO: "true" 
  MONGO_URL: "mongodb://mongodb:27017/catalogue"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalogue
  namespace: roboshop
  labels: #repica set labels
    name: catalogue
    environment: dev
    type: app
spec:
  replicas: 1
  selector: # These are the labels replica set use to create pod replicas, this should match pod labels
    matchLabels:
      name: catalogue
      environment: dev
      type: app
  template: # This is pod definition
    metadata:
      name: catalogue
      labels: 
        name: catalogue
        environment: dev
        type: app
    spec:
      containers:
      - name: catalogue
        image: kusumasoumya/catalogue:v1
        envFrom:
        - configMapRef:
            name: mongodb-configmap
---
apiVersion: v1
kind: Service
metadata:
  name: catalogue
  namespace: roboshop
  labels: 
    name: catalogue
    environment: dev
    type: app
spec:
  selector:
    name: catalogue
    environment: dev
    type: app
  ports:
    - protocol: TCP
      port: 8080 #service port
      targetPort: 8080 #container port


