apiVersion: v1
kind: ConfigMap
metadata:
  name: payment-configmap
  namespace: roboshop
  labels:
    name: payment
    environment: dev
    type: app
data:
  CART_HOST: "cart"
  CART_PORT: "8080"
  USER_HOST: "user"
  USER_PORT: "8080"
  AMQP_HOST: "rabbitmq"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment
  namespace: roboshop
  labels: #repica set labels
    name: payment
    environment: dev
    type: app
spec:
  replicas: 1
  selector: # These are the labels replica set use to create pod replicas, this should match pod labels
    matchLabels:
      name: payment
      environment: dev
      type: app
  template: # This is pod definition
    metadata:
      name: payment
      labels: 
        name: payment
        environment: dev
        type: app
    spec:
      containers:
      - name: payment
        image: kusumasoumya/payment:v1
        envFrom:
        - configMapRef:
            name: payment-configmap
---
apiVersion: v1
kind: Service
metadata:
  name: payment
  namespace: roboshop
  labels: 
    name: payment
    environment: dev
    type: app
spec:
  selector:
    name: payment
    environment: dev
    type: app
  ports:
    - protocol: TCP
      port: 8080 #service port
      targetPort: 8080 #container port


