apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: roboshop
  labels: #repica set labels
    name: redis
    environment: dev
    type: database
spec:
  replicas: 1
  selector: # These are the labels replica set use to create pod replicas, this should match pod labels
    matchLabels:
      name: redis
      environment: dev
      type: database
  template: # This is pod definition
    metadata:
      labels: 
        name: redis
        environment: dev
        type: database
    spec:
      containers:
      - name: redis
        image: redis:7.0
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: roboshop
  labels: 
    name: redis
    environment: dev
    type: database
spec:
  selector:
    name: redis
    environment: dev
    type: database
  ports:
    - protocol: TCP
      port: 6379 #service port
      targetPort: 6379 #container port
